development:
  adapter: postgresql
  host: localhost
  database: its_nacho_problem_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  host: localhost
  database: its_nacho_problem_test
  pool: 5
  min_messages: warning
  username: 
  password:

production:
  adapter: postgresql
  host: localhost
  database: its_nacho_problem_production
  pool: 5
  username: 
  password:
